import '../styles/globals.css'
import '../styles/pages.sass'
import '/components/map/map.styles.sass'
import '/components/form/form.styles.sass'
import '/components/nav/nav.styles.sass'
import '/components/footer/footer.styles.sass'
import type {AppProps} from 'next/app'
import Nav from "../components/nav/nav.component";
import Head from "next/head";
import Footer from "../components/footer/footer.component";
import styles from '../styles/Homu.module.sass'

function MyApp({Component, pageProps}: AppProps) {
    return (
        <>
            <Head>
                <title>Eugene Suhanov</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.container}>
                <Nav/>
                <Component {...pageProps} Nav={Nav}/>
            </div>
            <Footer/>
        </>
    )
}

export default MyApp
